sudo: required
language: generic 
services:
    - docker

# this stuff happens before our tests our ran
before_install:
    - docker build -t hackerman4047/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true hackerman4047/docker-react npm run test 

